using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ELECTIVE
{
    internal class Product
    {
        // Properties (characteristics) of a product
        // These match the columns in our database table

        /// <summary>
        /// Unique identifier for the product
        /// Auto-generated by the database
        /// </summary>
        public int ProductID { get; set; }

        /// <summary>
        /// Barcode of the product (unique)
        /// This is what the barcode reader will read
        /// </summary>
        public string Barcode { get; set; }

        /// <summary>
        /// Name of the product
        /// Example: "Apple Juice 1L"
        /// </summary>
        public string ProductName { get; set; }

        /// <summary>
        /// Category of the product
        /// Example: "Food", "Electronics", "Clothing"
        /// </summary>
        public string Category { get; set; }

        /// <summary>
        /// How many units we have in stock
        /// Example: 50 (meaning 50 bottles)
        /// </summary>
        public int Quantity { get; set; }

        /// <summary>
        /// Price of one unit
        /// Example: 2.99 (dollars/pesos/etc)
        /// </summary>
        public decimal Price { get; set; }

        /// <summary>
        /// Date when the product expires
        /// Example: "2025-12-31"
        /// This can be NULL for products that don't expire
        /// </summary>
        public DateTime? ExpirationDate { get; set; }

        /// <summary>
        /// Date when the product was manufactured
        /// Example: "2024-01-15"
        /// This can be NULL if unknown
        /// </summary>
        public DateTime? ManufacturingDate { get; set; }

        /// <summary>
        /// Unit of measurement
        /// Example: "pcs" (pieces), "kg" (kilograms), "L" (liters)
        /// </summary>
        public string Unit { get; set; }

        /// <summary>
        /// Detailed description of the product
        /// Example: "Fresh organic apples from local farm"
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Path to the product image file
        /// Example: "C:\Products\apple.jpg"
        /// This can be NULL if no image
        /// </summary>
        public string ImagePath { get; set; }

        /// <summary>
        /// Supplier/Vendor of the product
        /// Example: "Fresh Foods Inc."
        /// </summary>
        public string Supplier { get; set; }

        /// <summary>
        /// When this product record was created
        /// Auto-set by the database
        /// </summary>
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// When this product record was last updated
        /// Auto-updated by the database
        /// </summary>
        public DateTime UpdatedDate { get; set; }

        // Constructor - helps create a new Product easily
        public Product()
        {
            // Set default values
            Quantity = 0;
            Price = 0;
        }

        // Override ToString for easy debugging
        public override string ToString()
        {
            return $"{ProductName} - Barcode: {Barcode} - Price: ${Price} - Qty: {Quantity}";
        }
    }
}
